# Generated by Django 6.0.3 on 2026-04-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_client_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='debt',
        ),
    ]
